### ISSUE TITLE
sqlitebrowser can read/write the .instrument db

### ISSUE THREAD

**Issue by eakwarren** [CarlGao4/Muse-Sounds#1]
[https://sqlitebrowser.org](https://sqlitebrowser.org) can read/write the .instrument database. 
<img width="1601" alt="Screenshot 2024-06-22 at 11 13 45 PM" src="https://github.com/CarlGao4/Muse-Sounds/assets/1768096/2e7e0048-1853-41d7-ac47-913ad521bc5b">

**Comment by CarlGao4** [comment]
Thanks!
