### ISSUE TITLE
Switching presets

### ISSUE THREAD

**Issue by eakwarren** [CarlGao4/Muse-Sounds#4]
"Currently, I don't know how to switch to "Harmonics" and "Tremolo" presets. Similar to the Harp, many other soundfonts have multiple presets but I can only extract part of them. As I only play Piano, I hope that someone familiar with those instruments can help me to extract all presets."

Are you talking about how to activate Harmonics and Tremolo in MuseScore to then extract from RAM? If so, https://musescore.org/en/handbook/4/notation-expressive-markings may be helpful as it shows how to activate certain playing styles. For example, https://musescore.org/en/handbook/4/tremolo-and-rolls and https://musescore.org/en/handbook/4/articulations and https://musescore.org/en/handbook/4/ornaments all provide great info.

Specifically, harmonics can be applied with the o symbol or text, and tremolo with text or various symbols.
<img width="301" alt="Screenshot 2024-07-23 at 3 38 31 PM" src="https://github.com/user-attachments/assets/5e01188e-33f9-4782-9303-3ca2d63236a4">
<img width="298" alt="Screenshot 2024-07-23 at 3 40 07 PM" src="https://github.com/user-attachments/assets/71c01656-4530-41b1-b530-9a9595c5c472">
<img width="294" alt="Screenshot 2024-07-23 at 3 48 37 PM" src="https://github.com/user-attachments/assets/0ae30352-5b43-4b32-882a-c0420159cc8b">

If a palette isn't showing, click Add Palettes in the top of the Palettes tab to enable it.

Hope this helps. :-)

**Comment by CarlGao4** [comment]
No, this is not what I mean. I can add these symbols, but it doesn't change the sample, and there is also no change when playing it

**Comment by CarlGao4** [comment]
However, with your help, I've successfully extracted tremolo sfz, thanks!
I'm still finding a method to extract harmonics

**Comment by CarlGao4** [comment]
I've successfully extracted all the files by modifying decrypted memory before it loads the file
